version: '3'
services:
  db:
    image: postgres:10.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    
volumes:
  postgres-data: